name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VERSION: 1.0-SNAPSHOT

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Java install
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Maven build
        run: mvn clean install -f pom.xml

      - name: zip docs
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r target/docs.zip target/apidocs

      - name: collect artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-plugin-${{ env.VERSION }}
          path: |
            target/docs.zip
            target/my-plugin-${{ env.VERSION }}.jar
          if-no-files-found: error